name: errorAction

on: 
  pull_request:
    branches: [master]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: Generate Error
      run: echo "::error::Error is thrown here message"
    - name: Generate Warning
      run: echo "warning ::Warning throw message"
