name: updateCertainPath

on: 
  push:
    paths:
    - 'sdk/compute/**'
  pull_request:
    paths: 
    - 'sdk/compute/**'

   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: CertainPathUpdated
      run: echo only the certain path updated
      
    - name: condition if push
      if: ${{ github.event_name == 'push' }}
      run: 
        echo push check succeeded;
        echo Error on push, exiting with 1;
        exit 1;
    - name: condition if pull_request
      if: ${{ github.event_name == 'pull_request' }}
      run: 
        echo pull request succeeded;
        echo Exiting with 0;
        exit 0;
    - name: find Sun text in file
      run: grep -q "Sun" sdk/compute/placeholderFile
